### ISSUE TITLE
Figure out story with csharp-decorators

### ISSUE THREAD

**Issue by ndrwrbgs** [ndrwrbgs/OpenTracing-EventHookTracer#11]
@jrouaix
The https://github.com/opentracing-contrib/csharp-decorators library and this one have a lot of overlap. From using that library, there are a few features that seem to be here but not there - support for Logs and Tags for instance, but over there has more complete documentation and more users.

This issue is to track figuring out what the story going forward should be. Should we continue to invest in two libraries with largely overlapping scenarios, or merge them and work on one.

Please let me know what you'd like best!

**Comment by jrouaix** [comment]
@ndrwrbgs you're right. Give me few days to properly answer you and come up with a plan to merge our efforts ?

**Comment by ndrwrbgs** [comment]
Thanks. Please note that if are welcome to contributions I'm absolutely okay switching over my usages of this library to yours and porting features with pull requests as I need them. The primary CON here I think would be that I would request your engagement as owner to discuss design decisions or possible changes before making them, which would add some more work for you.

**Comment by jrouaix** [comment]
Hello @ndrwrbgs, I just pushed some Tags & Logs interception in the /dev banch.

I'd be very glad to accept PRs & discussions or design advices. This lib was a attempt to reach an other goal : https://github.com/jrouaix/AppMetrics.OpenTracing, kind off not my priority in the moment but still in the backlog.

I can see your design is build around events, while mine is around delegate/decorator and some kind of builder syntax.
To be honest, I can see people who would like yours or mine. They are just coding styles.
I think we can really extend your kind of design in mine :
```
builder.WithEvents(events =>{
   events.OnSpanStarted += (span, operationName) => {};
   events.OnSpanFinished += (span, operaitonName) => {};
   // ....
});
```
with the WithEvents method doing the dirty job to plug all the events in the proper delegate call.

By the way, if you smell something odd in the existing code ... you are very welcome to say.
And I have to do more unit tests right now.

**Comment by ndrwrbgs** [comment]
Yeah I don't care about the style as long as the functionality is there, since if functionality is there a wrapper library is always possible for style changes.

I will Archive my project then and begin to switch my usage over to your library!

**Comment by jrouaix** [comment]
Just sent the new version in Nuget : https://www.nuget.org/packages/OpenTracing.Contrib.Decorators/

**Comment by ndrwrbgs** [comment]
Coming back to this super late, I think the biggest thing will be this library (EventHookTracer) is doing both decoration & AsyncLocal propagation. Those need to be separated out.

**Comment by jrouaix** [comment]
Hello @ndrwrbgs I don't see where you "asyncLocal" propagate the events ? you have a code sample ?

**Comment by ndrwrbgs** [comment]
https://github.com/ndrwrbgs/OpenTracing-EventHookTracer/blob/80d36340793fecb9109b83131c1dc6406a08370e/src/Library/EventHookScopeManager.cs#L44



I've been successfully using the Decorator project [example](https://github.com/ndrwrbgs/OpenTracing-LocalTracers), but it really requires a functional underlying tracer. For test applications, I've used the [MockTracer](https://github.com/opentracing/opentracing-csharp/blob/c534179959d4a4160e06456cc70e609f827952e8/src/OpenTracing/Mock/MockTracer.cs) that exists in the OpenTracing library, but that would be bad for real applications as it holds everything in memory.

I guess if we had a BasicTracer package (https://github.com/opentracing/opentracing-csharp/issues/48) that did propagation (unlike NoopTracer) and wasn't targeted at test scenarios (like MockTracer is), that would work well to fill the only remaining gap.
